/**
 * Created by ds on 24/04/2016.
 *
 */

var fs = require('fs');
var alleleFreq = require('./lib/allele-frequencies');

/*
   Return from variant query. In this case as a string?
 */
var variants = 'sid   cid      pos      alt nalt ref nref\n\
            1    1   chr17   41196408   A    1   G    1\n\n\
            2    1   chr17   41197274   A    1   C    1\n\
            3    2   chr17   41196841   T    1   G    1\n\
            4    3   chr17   41196408   A    1   G    1\n\
            5    3   chr17   41197274   A    1   C    1\n\
            6    6   chr17   41196408   A    1   G    1\n\
            7    6   chr17   41197274   A    1   C    1\n\
            8   10   chr17   41196408   A    1   G    1\n\
            9   10   chr17   41197274   A    1   C    1';

/*
    Reference sequence
 */
var refs = "TGGAAGTGTTTGCTACCAAGTTTATTTGCAGTGTTAACAGCACAACATTTACAAAACGTATTTTGTACAATCAAGTCTTCACTGCCCTTGCACACTGGGGGGGCTAGG" +
    "GAAGACCTAGTCCTTCCAACAGCTATAAACAGTCCTGGATAATGGGTTTATGAAAAACACTTTTTCTTCCTTCAGCAAGCAAAATTATTTATGAAGCTGTATGGTTTCAGCAACA" +
    "GGGAGCAAAGGAAAAAAATCACCTCAAAGAAAGCAACAGCTTCCTTCCTGGTGGGATCTGTCATTTTATAGATATGAAATATTCATGCCAGAGGTCTTATATTTTAAGAGGAATG" +
    "GATTATATACCAGAGCTACAACAATAAACATTTTACTTATTACTAATGAGGAATTAGAAGACTGTCTTTGGAAACCGGTTCTTGAAAATCTTCTGCTGTTTTAGAACACATTCTT" +
    "TAGAAATCTAGCAAATATATCTCAGACTTTTAGAAATCTCTTCTAGTTTCATTTTCCTTTTTTTTTTTTTTTTTTTGAGCCACAGTCTCACTGTCACCCAGGCTGGAGTGCCGTG" +
    "GTATGATCTTGGCTCACTGCAACCTCCACCTCCCGGGCTGAAGTGATTCTCCTGCCTTAGCCACCTGAGTAGCTGGGATTACAGGTGTCCACCACCATGACCGGCTAATTTCTGT" +
    "ATTTTTAGTAGAGATGGGGTTTCACCATGTTGGCCAGGCTGGTTTCGAACTCCTGACCTCCAGTGATCTGCCCACCTTGGCCTCCCAAAGTGCTGGGATTACAGGCGTGAGCCAC" +
    "CATGCCCAGGTTTCAAGTTTCCTTTTCATTTCTAATACCTGCCTCAGAATTTCCTCCCCAATGTTCCACTCCAACATTTGAGAACTGCCCAAGGACTATTCTGACTTTAAGTCAC" +
    "ATAATCGATCCCAAGCACTCTCCTTCCATTGAAGGGTCTGACTCTCTGCCTTTGTGAACACAGGGTTTTAGAGAAGTAAACTTAGGGAAACCAGCTATTCTCTTGAGGCCAAGCC" +
    "ACTCTGTGCTTCCAGCCCTAAGCCAACAACAGCCTGAATAGAAAGAATAGGGCTGATAAATAATGAATCAGCATCTTGCTCAATTGGTGGCGTTTAAATGGTTTTAAAATCTTCT" +
    "CAGGTGAAAAATTACCATAATTTTGTGCTCATGGCAGATTTCCAAGGGAGACTTCAAGCAGAAAATCTTTAAGGGACCCTTGCATAGCCAGAAGTCCTTTTCAGGCTGATGTACA" +
    "TAAAATATTTAGTAGCCAGGACAGTAGAAGGACTGAAGAGTGAGAGGAGCTCCCAGGGCCTGGAAAGGCCACTTTGTAAGCTCATTCTTGGGGTCCTGTGGCTCTGTACCTGTGG" +
    "CTGGCTGCAGTCAGTAGTGGCTGTGGGGGATCTGGGGTATCAGGTAGGTGTCCAGCTCCTGGCACTGGTAGAGTGCTACACTGTCCAACACCCACTCTCGGGTCACCACAGGTGC" +
    "CTCACACATCTGCCCAATTG";


var range = 'Chr17:41,196,312-41,197,819';
var samples = "1,2,3,5,6,10".split(',');


var counter = new alleleFreq(samples, range, refs, variants);
counter.read();
counter.calculateFrequencies();
counter.writeToFile("allele-freq-output.txt");

console.log(counter.getFrequencies()[97]);
console.log(counter.getFrequencies()[530]);
console.log(counter.getFrequencies()[963]);
